### ISSUE TITLE
Figure out live window

### ISSUE THREAD

**Issue by cglagovich** [FRCTeam3182/FRC2017#24]
We want to use the smart dashboard to display information such as the sensors' information. We should do this in test mode first, and make it so that we can do real-time PID tuning on the encoders. Live window may be the correct tool to use, but we haven't been able to figure out how to use it. Smart dashboard seems to work, but we don't know if it can be used to tune like live window. In an example on the FRC website, they used the live window to change the P, I, D, and F valued while monitoring the output.

**Comment by motleymentor** [comment]
We've gotten all the LiveWindow stuff done. Now we're using it to tune the PID in #23.
