### ISSUE TITLE
ROBOTVISION

### ISSUE THREAD

**Issue by cglagovich** [FRCTeam3182/FRC2017#28]
Finish up the vision on the Raspberry Pi that can detect shapes and will eventually guide the robot in competition. This issue can be resolved when vision works and can be implemented into driving.

**Comment by motleymentor** [comment]
As of last meeting (Wednesday because of the bad weather), @PizzaFriday was able to see contours in GRIP of the reflective tape. Today, we will:

- [x] Build a camera target with all the [same dimension](https://firstfrc.blob.core.windows.net/frc2017/Manual/2017FRCGameSeasonManual.pdf) of the real fields reflective target around the Peg.
- [x] Adjust the HSV and other qualities of the image to detect the camera target.
- [x] Determine the best information for the GRIP pipeline to send to the roboRio.
- [x] Deploy pipeline to the Raspberry Pi

**Comment by motleymentor** [comment]
@PizzaFriday and I came up with the following pipeline written here in the proper order as pseudo code. We implemented this in the GRIP user interface. Anything with (D) is the default value.

1. CV Resize:
   - fx, fy = 0.25 (D);
   - interp = interlinear (D);
2. HSV Threhold:
   - H = 44-45;
   - S = 0-7;
   - V = 240-255;
3. CV Erode:
   - iterations = 1 (D);
   - border type = border constant (D);
4. Find Contours
5. Filter Contours
   - minArea = 25;
   - minPerim = 0;
   - minWidth = 0; maxWidth = 35;
   - minHeight = 0; maxHieght = 85;
   - solidity = 90-100;
   - maxVerts = 18; minVerts = 4;
   - minRatio = 0 (D); maxRatio = 1000 (D);
6. Publish Contours

**Comment by motleymentor** [comment]
From the [Vision processing on an Arm coprocessor](http://wpilib.screenstepslive.com/s/4485/m/24194/l/682949) wiki page, @PizzaFriday and I found the `detect-raspbian` command works, while the `detect-hf` does not. This means raspbian is the "proper artifact" and we do not need to build all artifacts for the Pi.

@kiallsop made the boilerplate Main.java that ran on the Pi to send the image to the SmartDashboard. We've created a new PiVision branch in 5bdedf302a22ebe229d4cd20edc3cebd4ff17afe with his code and added the grip pipeline. The new build for the Pi is in 927d52019f5c787a55c4525f0a1d4795ba5d0f5e. Testing it now...

**Comment by PizzaFriday** [comment]
#30 Pull request for Pi Vision.

**Comment by motleymentor** [comment]
There's till some testing we need to do, but we're looking good right now! :)

**Comment by kiallsop** [comment]
Programmers:

The 3rd post in this thread has example java code for roborio & coprocessor
to write and read networktable variables:
https://www.chiefdelphi.com/forums/showthread.php?t=155206

The coprocessor (Pi) networktables code is very close to what is already in
the Main.java Pi code (not the GRIP generated code).

There is a debug tool to inspect/change networktable variables:
http://wpilib.screenstepslive.com/s/3120/m/7912/l/84115-using-tableviewer-to-see-networktable-values

It looks like the GRIP contours list<MatOfPoints> may need to be copied
to/from an equivalent java table (or cast), I did not see a way to directly
put the list<> onto networktables.

I was hoping to attend for part of tonight but won't be able to. I can
support Suffield on Saturday if we go, and would have the minivan which can
seat 7 (including driver).
